name: ZHA Device Status
version: "1.0"
slug: zha_device_status
description: Tracks and displays Zigbee device data from ZHA
startup: services
boot: auto
init: false
ingress: false
panel_title: ZHA Status
panel_icon: mdi:zigbee
panel_admin: false
webui: http://[HOST]:5000
ports:
  5000/tcp: 5000
map:
  - config:rw
options:
  ha_token: ""
schema:
  ha_token: str

