name: ZHA Device Status
version: "0.99981"
slug: zha_status
description: Tracks and displays Zigbee device data from ZHA
startup: services
boot: auto
init: false
ingress: false
panel_title: ZHA Device Status
panel_icon: mdi:zigbee
panel_admin: false
webui: http://[HOST]:[PORT:5000]
ports:
  5000/tcp: 5000
map:
  - config:rw
arch:
  - amd64
  - aarch64
  - armv7

options:
  ha_token: ""
  use_ssl: true
  debug: false
  offline_threshold_minutes: 60

schema:
  ha_token: str
  use_ssl: bool
  debug: bool
  offline_threshold_minutes: int
